  
experiment:
  id: "sample"
  input_data:
    root: "./data/sample-data/"
  outdir: "./data/sample-data/out/"
  subjects: [
    "02",
    "27",
  ]
  objects: [
    'Kerze',
    'Vase',
    'Blume',
    'Tasse',
    'Rose',
  ]
  fillers: [
    'Tube',
    'Dose',
    'Flasche',
    'Pflanze',
    'Creme',
    'Spritze',
    'Paste',
  ]

